### ISSUE TITLE
java.util.ConcurrentModificationException on getFuture

### ISSUE THREAD

**Issue by jlerbsc** [mikroskeem/PicoMaven#12]
Hi, when i try to follow your exemple i get this ConcurrentModificationException 

    Caused by: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at MyApp.getFuture
	... 15 more
	[CIRCULAR REFERENCE:java.util.ConcurrentModificationException]

**Comment by mikroskeem** [comment]
Thanks for reporting. I have never tested the example really, it's rather for giving people an idea how to use the library. Follow correct concurrency practices (which I am clearly not doing in the example) and this error won't happen.
